name: historica
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  audioplayers: 0.17.0
  shared_preferences: 0.5.12+4
  percent_indicator: ^3.0.1
  mailto: ^2.0.0
  url_launcher: ^5.7.10
  flutter_tts: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/
    - images/ashoka/
    - images/rama/
    - images/apj/
    - images/chanakya/
    - images/pandava/
    - images/cv/
    - images/card/
    - images/card/home/
    - images/card/history/
    - images/card/mythology/
    - images/card/scientist/
    - images/logo/
    - images/backgrounds/
    - assets/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf

